### ISSUE TITLE
HTMLUnit does not process JavaScript fetch

### ISSUE THREAD

**Issue by Procambarus-gracilis** [HtmlUnit/htmlunit#148] opened 2020-03-23 01:09 UTC
I am trying to write a scraping tool to obtain the string COC1=CC2=C(C=C1)NC3=C2CCNC3 from the section titled "Canonical SMILES" from the following website (it uses some sort of dynamic JavaScript content loading when you scroll to the aforementioned "Canonical SMILES" section of the page): https://pubchem.ncbi.nlm.nih.gov/compound/1868

Until about 2 days ago, I had functioning code (thanks Ronald), but it appears that the webmaster of the above site has very recently introduced a new JavaScript library that uses some server request/response facilitator called "fetch" which renders my present code unusable.  Now, instead of printing out my target string (COC1=CC2=C(C=C1)NC3=C2CCNC3), running the HTMLUnit code instead returns:

_SEVERE: ReferenceError: "fetch" is not defined_

I tried including the following in order to supress this error and see if my code would run anyways:

_webClient.getOptions().setThrowExceptionOnScriptError(false);_

but I still got the error.

After discussing the situation on the mailing list, I have thus decided to post this issue here.

Will this situation ultimately require a new version of HTMLUnit?  Below is the main method I am using.  Thanks.

`
public static void main(String[] args) throws Exception {

String uri = "https://pubchem.ncbi.nlm.nih.gov/compound/1868";

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX)) {
          // do not stop on js errors
          webClient.getOptions().setThrowExceptionOnScriptError(false);
          // do not log js errors (usually using this is a bad idea, at least
          // if you are hunting for problems).
          webClient.setJavaScriptErrorListener(new SilentJavaScriptErrorListener());

          HtmlPage page = webClient.getPage(uri);
          webClient.waitForBackgroundJavaScriptStartingBefore(10_000);

          final DomNodeList<DomNode> divs = page.querySelectorAll("#Canonical-SMILES .section-content .section-content-item p");
          for (DomNode div : divs) {
              System.out.println("----------------");
              System.out.println(div.asXml());
              System.out.println("----------------");
              System.out.println(div.asText());
              System.out.println("----------------");
          }
        }
    }`

**Comment by rbri** [comment] 2020-03-23 07:45
Will have a look

**Comment by udittmer** [comment] 2020-05-06 08:50
Dup of https://github.com/HtmlUnit/htmlunit/issues/78?

**Comment by rbri** [comment] 2020-10-14 18:09
Yes this is a duplicate of #78. Did not found the time to work on this. Any help is welcome.

**Closed as completed by rbri** 2020-10-14 18:09 UTC
