### ISSUE TITLE
java.lang.IllegalStateException: No script object associated with the Page

### ISSUE THREAD

**Issue by rmbarnett-rice** [HtmlUnit/htmlunit#171] opened 2020-05-12 22:46 UTC
```
May 12, 2020 5:42:24 PM com.gargoylesoftware.htmlunit.WebClient close
SEVERE: Exception while closing a topLevelWindow
java.lang.IllegalStateException: No script object associated with the Page. class: 'com.gargoylesoftware.htmlunit.html.HtmlPage' url: 'https://127.0.0.1:4443/thanks.html' content: <!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/main.css">

    <title>CovidSense</title>
</head>
<body>

<div id="header">
    CovidSense
</div>

<h2>
    <br>
    <br>
    <br>
    <br>
    Thanks for your participation! We truly appreciate it.<br>
    <br>
    <br>
    We will also appreciate if you could encourage your adult family members, friends and colleagues (who have their own mobile phones) to participate in the study. You can forward them the following text.
    <br>
    <br>
    I am a participant in this citizen science project on Covid-19 pandemic. I thought you might be interested. You can join the study at www.covidsense.org .</h2>

    <script>
    </script>
</body>
</html>
	at com.gargoylesoftware.htmlunit.html.DomNode.getScriptableObject(DomNode.java:945)
	at com.gargoylesoftware.htmlunit.javascript.host.event.Event.<init>(Event.java:217)
	at com.gargoylesoftware.htmlunit.javascript.host.event.BeforeUnloadEvent.<init>(BeforeUnloadEvent.java:71)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeEventHandlersIfNeeded(HtmlPage.java:1240)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.isOnbeforeunloadAccepted(HtmlPage.java:1320)
	at com.gargoylesoftware.htmlunit.TopLevelWindow.close(TopLevelWindow.java:115)
	at com.gargoylesoftware.htmlunit.WebClient.close(WebClient.java:2079)
```

**Comment by rbri** [comment] 2020-09-19 14:58
It will be great if you can create a simple sample to reproduce this.

**Comment by rbri** [comment] 2020-10-16 22:00
Looks like a duplicate of #68. Please use the latest snapshot or the upcoming version 2.45.

**Closed as completed by rbri** 2020-10-16 22:00 UTC
