### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot locate declared field class org.apache.http.impl.client.HttpClientBuilder.dnsResolver

### ISSUE THREAD

**Issue by vikramvi** [HtmlUnit/htmlunit#553] opened 2023-02-27 06:16 UTC
Reference:

[https://devpal.co/blog/web-scraping-with-java-and-htmlunit/](https://devpal.co/blog/web-scraping-with-java-and-htmlunit/
)

I am doing exactly same steps as mentioned in the blog but getting error

_java.lang.IllegalArgumentException: Cannot locate declared field class org.apache.http.impl.client.HttpClientBuilder.dnsResolver
for the below call_

`HtmlPage myPage = webClient.getPage("https://devpal.co");
`

pom.xml entry

https://gist.github.com/vikramvi/05073952de1a0b18c1863d80ef93b75a

```
<dependency>
    <groupId>net.sourceforge.htmlunit</groupId>
    <artifactId>htmlunit</artifactId>
    <version>2.70.0</version>
</dependency>
```

**Comment by vikramvi** [comment] 2023-02-27 06:46
Some more findings


I did System.out.println(HttpClientBuilder.class.getProtectionDomain().getCodeSource().getLocation()); and it's pointing to "file:/Users/vikramanna/.m2/repository/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar", how can I make it to point to correct version of httpclient ?

References : 

[sqa.stackexchange.com/questions/20137/htmlunit-driver-error](https://sqa.stackexchange.com/questions/20137/htmlunit-driver-error)

[sourceforge.net/p/htmlunit/bugs/1786](https://sourceforge.net/p/htmlunit/bugs/1786/)

Question ?

Is is necessary to include httpclient explicitly in pom.xml or it should be picked up from htmlunit itself ?

**Comment by rbri** [comment] 2023-02-27 07:20
HtmlUnit 2.70.0 uses HttpClient 4.5.14. This dependency is resolved by maven automatically - as long as you do not have other libs in your pom pointing to other versions of the HttpClient (this is named a conflict in maven and you have to deal with this).

You are running your code on android?

**Comment by vikramvi** [comment] 2023-02-27 08:29
Thanks for the comment, please find additional info.

> You are running your code on android?

No, this code is run for a web application. 


Can you please check pom.xml and clarify why 4.5.14 is not getting picked and instead program is pointing to older version ?

**Comment by rbri** [comment] 2023-02-27 08:35
i guess Idea can do this for you....

In Eclipse it looks like this
![image](https://user-images.githubusercontent.com/2544132/221513736-cdedab81-7217-42f6-908a-adc4213e2845.png)

**Comment by rbri** [comment] 2023-02-27 08:36
and by the way - there is no need to have jsoup and htmlunit together - hopefully HtmlUnit can do everything jsoup can do (and adds javascript support)

**Comment by vikramvi** [comment] 2023-02-28 06:28
@rbri thanks for your help, I could get the issue fixed. The problem was that I was using quite older version of phantomjsdriver; which was pointing to older version of HTTPClient.

Regarding your comment

> there is no need to have jsoup and htmlunit together

Can you please check below ?

https://stackoverflow.com/questions/75553133/jsoup-returns-document-even-when-some-portion-of-page-is-not-fully-loaded

I tried to fix using solution from 

https://stackoverflow.com/questions/6368045/jsoup-fetching-a-partial-page

but it's throwing weird exceptions.

What's the best way to handle AJAX / JS calls made post loading page to scrape data ?

**Comment by rbri** [comment] 2023-03-03 13:53
The best way is simply to let HtmlUnit do the job.
If you get problems, please open an issue and include a reproducible sample and i try to help.

**Closed as completed** 2023-03-07 07:06 UTC

**Comment by rbri** [comment] 2023-03-07 07:51
Hope this works for you - thanks for using HtmlUnit.
