### ISSUE TITLE
How to upload multiple files in <input multiple> with HtmlUnit ?

### ISSUE THREAD

**Issue by smxc** [HtmlUnit/htmlunit#112] opened 2019-12-19 01:13 UTC
code:
`			
fileInput.setContentType("image/jpeg");

fileInput.setValueAttribute(path + "/" + "1.jpg");

System.out.println("fileInputValue=" + fileInput.getValueAttribute());
`

fileInput.getValueAttribute() return null

**Comment by rbri** [comment] 2019-12-20 18:47
You can use com.gargoylesoftware.htmlunit.html.HtmlFileInput.setFiles(File...) to provide many files

Here a sample from the unit test suilt

        final String filename1 = "HtmlFileInputTest_one.txt";
        final String path1 = getClass().getResource(filename1).toExternalForm();
        final File file1 = new File(new URI(path1));
        assertTrue(file1.exists());

        final String filename2 = "HtmlFileInputTest_two.txt";
        final String path2 = getClass().getResource(filename2).toExternalForm();
        final File file2 = new File(new URI(path2));
        assertTrue(file2.exists());

        final WebClient client = getWebClient();
        final HtmlPage firstPage = client.getPage(URL_FIRST + "upload1");

        final HtmlForm form = firstPage.getForms().get(0);
        final HtmlFileInput fileInput = form.getInputByName("myInput");
        fileInput.setFiles(file1, file2);

        final HtmlSubmitInput submitInput = form.getInputByValue("Upload");
        final HtmlPage secondPage = submitInput.click();

**Comment by rbri** [comment] 2019-12-20 19:29
Have added some words to the documentation - will be available on the web site with the next release.
Thanks for the question; enjoy using HtmlUnit

**Comment by smxc** [comment] 2019-12-23 14:44
thanks, but it didn't work。

========================================================
code:

HtmlFileInput fileInput = (HtmlFileInput) createGoodsPage.getFirstByXPath("//div[@class='step-02']//div[@class='account-info']//div[@class='form-item clearfix'][1]//input[@name='file']");
String path = "D:/work/mydir/" + gameGoodsEntity.getGameAccount();
File[] files = FileUtil.getFiles(path, 10);
fileInput.setFiles(files);
webclient.waitForBackgroundJavaScript(10000);

HtmlAnchor sumibtAnchor = createGoodsPage.getFirstByXPath("//div[@class='step-02']//div[@class='form-footer']//a[@class='com-btn-01 color01 btn-submit']");
sumibtAnchor.click();

========================================================
the error message is：

22:27:02.971 logback [JS executor for com.gargoylesoftware.htmlunit.WebClient@407f2029] INFO  c.g.h.javascript.JavaScriptEngine - Caught script exception
com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot read property "size" from undefined (https://static.uhaozu.com/zuhao/common/uploader/webuploader.min.js#1)

**Comment by rbri** [comment] 2019-12-23 15:34
Ok, looks like the page uses https://github.com/fex-team/webuploader/tree/master/dist.
Will have a look at that, maybe there is a chance to find the problem.

**Comment by rbri** [comment] 2019-12-23 15:38
Because the web pages are in Chinese - it will be great if you can prepare a simple sample html page that shows the problem.

**Comment by smxc** [comment] 2019-12-25 13:19
sample html page:
==================================
&lt;div class="account-info">
    &lt;div class="common-form">
        &lt;div class="form-item clearfix">
            &lt;div class="form-item-l"><i>*</i><span&gt;上传游戏截图：&lt;/span></div&gt;
            &lt;div class="form-item-r">
                &lt;div class="upload-con screenshot-upload-box">
                    &lt;div id="uploader-demo">
                        &lt;div id="filePicker&quot; class="webuploader-container">
						&lt;div class="webuploader-pick">上传图片&lt;/div&gt;
							&lt;div id="rt_rt_1dsuik18k9q41n0m150lia8vfs1&quot; style="position: absolute; top: 0px; left: 0px; width: 82px; height: 32px; overflow: hidden; bottom: auto; right: auto;">
								&lt;input type="file&quot; name="file&quot; class="webuploader-element-invisible&quot; multiple="multiple&quot; accept="image/jpg,image/jpeg,image/png"><label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label&gt;
							&lt;/div&gt;
						&lt;/div&gt;
                        &lt;div id="fileList&quot; class="uploader-list">
							&lt;div class="file-item thumbnail upload-state-done">
								&lt;img src="//picture.uhaozu.com/2019/47/20/6876fd10a95c4f57a4cd8944d720db10.JPG">
								&lt;div class="remove-this out-data"></div&gt;
							&lt;/div&gt;
							&lt;div class="file-item thumbnail upload-state-done">
								&lt;img src="//picture.uhaozu.com/2019/47/20/9f60ba96ecdc460285f43a9c90ce2c85.JPG">
								&lt;div class="remove-this out-data"></div&gt;
							&lt;/div&gt;
							&lt;div class="file-item thumbnail upload-state-done">
								&lt;img src="//picture.uhaozu.com/2019/47/20/2dcf08a1b660419f98a4558951f6bff7.JPG">
								&lt;div class="remove-this out-data"></div&gt;
							&lt;/div&gt;
							&lt;div class="file-item thumbnail upload-state-done">
								&lt;img src="//picture.uhaozu.com/2019/47/20/ddff6fdd296f4bdfb3dd4ed61883b6b8.JPG">
								&lt;div class="remove-this out-data"></div&gt;
							&lt;/div&gt;
							&lt;div class="file-item thumbnail upload-state-done">
								&lt;img src="//picture.uhaozu.com/2019/47/20/c605eeabc5ac4b89b37dee1c6bd30bed.JPG">
								&lt;div class="remove-this out-data"></div&gt;
							&lt;/div&gt;
						&lt;/div&gt;
                    &lt;/div&gt;
                    &lt;p class="form-item-tips">仅支持JPG、JPEG、PNG格式，文件小于2M&lt;em&gt;（最多上传10张图片，最少上传1张）&lt;/em></p&gt;
                    &lt;p class="upload-error-tips error">至少选择一张图片!</p&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;



upload.js :
================================
`
if(!window.fileUploaderServer) {　　　
	var fileUploaderServer = "//upload.uhaozu.com/oss/upload";　
} else {
	var fileUploaderServer = window.fileUploaderServer;
}

imgUrlList = [];
var $ = jQuery,
	$list = $('#fileList'),
	state = 'pending',
	// 优化retina, 在retina下这个值是2
	ratio = window.devicePixelRatio || 1,

	// 缩略图大小
	thumbnailWidth = 148 * ratio,
	thumbnailHeight = 148 * ratio,

	// Web Uploader实例
	uploader;

if(typeof(fileNumLimit) == "undefined") {
	fileNumLimit = 10;
}
// 初始化Web Uploader
uploader = WebUploader.create({
	//限制数量
	fileNumLimit: fileNumLimit,
	// 自动上传。
	auto: true,
	// 限制大小
	fileSingleSizeLimit: 2 * 1024 * 1024,
	// 去重
	duplicate: true,

	// swf文件路径
	swf: '//img.uhaozu.com/zuhao/common/uploader/Uploader.swf',

	// 文件接收服务端。
	server: fileUploaderServer,
	// 选择文件的按钮。可选。
	// 内部根据当前运行是创建，可能是input元素，也可能是flash.
	pick: '#filePicker',
	formData: {
		"userid": '111675301'
	},
	fileVal: 'file',
	// 只允许选择文件，可选。
	accept: {
		title: 'Images',
		extensions: 'jpg,jpeg,png',
		mimeTypes: 'image/jpg,image/jpeg,image/png'
	}
});

// 文件上传过程中
uploader.on('uploadProgress', function(file) {
	$(".screenshot-upload-box").find(".webuploader-pick").html("上传中...");
	$(".screenshot-upload-box").find(".upload-error-tips").hide().text("上传图片失败").removeClass("error");
});

// 文件上传成功，给item添加成功class, 用样式标记上传成功。
uploader.on('uploadSuccess', function(file, response) {
	var $li = $(
			'<div id="' + file.id + '" class="file-item thumbnail">' +
			'<img>' +
			'<div class="info">' + file.name + '</div>' +
			'<div class="remove-this"></div>' +
			'</div>'
		),
		$img = $li.find('img');
	$list.append($li);
	// 创建缩略图
	uploader.makeThumb(file, function(error, src) {
		if(error) {
			$img.replaceWith('<span>不能预览</span>');
			return;
		}

		$img.attr('src', src);

	}, thumbnailWidth, thumbnailHeight);
	$('#' + file.id).addClass('upload-state-done');
	$(".screenshot-upload-box").find(".webuploader-pick").html("上传图片");
	$("#big-img").find("img").attr("src", response.data);

	imgUrlList.push(response.data);
});

// 文件上传失败，显示上传出错。
uploader.on('error', function(type) {
	if(type == "Q_TYPE_DENIED" || type == "F_EXCEED_SIZE") {
		$(".screenshot-upload-box").find(".upload-error-tips").show().text("仅支持JPG、JPEG、PNG格式，文件小于2M").addClass("error");
	} else {
		$(".screenshot-upload-box").find(".upload-error-tips").show().text("上传图片失败").addClass("error");
	}
});

// 文件上传失败，显示上传出错。
uploader.on('uploadError', function(file) {
	$(".screenshot-upload-box").find(".upload-error-tips").show().text("上传图片失败").addClass("error");
});

$(".screenshot-upload-box").on('click', '.remove-this', function() {
	var _index = $(this).parents(".file-item").index();
	var _url = $(this).parents(".file-item").find("img").attr("src");
	$(this).parents(".file-item").remove();

	if(!$(this).hasClass("out-data")) {
		imgUrlList.splice(_index, 1);
		var id = $(this).parent().attr("id");
		var file = uploader.getFile(id);
		uploader.removeFile(file);
	} else {
		uploader.options.fileNumLimit++;
		removeImg(_url);
	}

});
`

submit：
=========================================================
`
$(function () {

    var submiting = false;

    function resetBtn() {
        submiting = false;
        $(".step-02").find('.btn-submit').html('立即发布').removeClass('disabled').addClass('color01');
    }

    //验证提交
    $(".step-02").Validform({
        btnSubmit: ".btn-submit",
        tiptype: 3,
        postonce: true, //for debug false
        ajaxPost: false,
        datatype: {
            "czsl": /^([0-9]|[1-9]\d{0,3})$/
        },
        errorNotify: function () {
            resetBtn();
        },
        beforeCheck: function () {
            if (submiting) {
                return false;
            }
            submiting = true;
            $(".step-02").find('.btn-submit').html('发布中...').addClass('disabled').removeClass('color01')
            var flag = 0;

            $(".step-02").find(".comselect.must").each(function () {
                if ($(this).find(".comselect-input").attr("data-value") == $(this).find(".comselect-input").attr("data-start")) {
                    $(this).addClass("Validform_error");
                    $(this).find(".comselect-input").focus();
                    flag = 1;
                    return false;
                }
            });
            if (flag !== 0) {
                resetBtn();
                return false;
            }
            if (preImgUrlList.length > 0 || imgUrlList.length > 0) { //判断是否选择了图片
                $(".screenshot-upload-box").find(".upload-error-tips").hide();
            } else {
                $(".screenshot-upload-box").find(".upload-error-tips").html("至少选择一张图片!");
                $(".screenshot-upload-box").find(".upload-error-tips").show();
                resetBtn();
                return false;
            }

        },
        beforeSubmit: function (curform) {
            var formData = {
                options: [],
                info: {},
                urls: preImgUrlList.concat(imgUrlList)
            };
            $('.step-01 input[name],.step-01 textarea[name],.step-02 input[name]').each(function () {
                var that = $(this),
                    type = that.attr('type'),
                    name = that.attr('name'),
                    isDataValue = typeof that.attr('data-option') !== 'undefined';
                if (!name) return;
                if (isDataValue) {
                    if (type == 'checkbox') {
                        if (that.prop('checked')) {
                            if (that.attr('data-true')) {
                                formData.options.push({
                                    optionId: that.attr('data-true')
                                });
                            }
                        } else {
                            if (that.attr('data-false')) {
                                formData.options.push({
                                    optionId: that.attr('data-false')
                                });
                            }
                        }
                        return;
                    }

                    var split = that.attr('data-split');
                    if (split) {
                        var array = that.val().split(split);
                        for (var i = 0, len = array.length; i < len; i++) {
                            if (array[i]) {
                                formData.options.push({
                                    optionId: array[i]
                                })
                            }
                        }
                        return;
                    }

                    if (typeof that.attr('data-name') !== 'undefined') {
                        formData.options.push({
                            optionId: name,
                            optionName: that.val()
                        });
                        return;
                    }

                    if (typeof that.attr('data-num') !== 'undefined') {
                        if (that.parent().parent().hasClass('on')) {
                            formData.options.push({
                                optionId: name,
                                optionNum: that.val()
                            });
                        }
                        return;
                    }

                    formData.options.push({
                        optionId: that.val()
                    });
                    return;
                }

                if (type == 'checkbox') {
                    var hasRevert = typeof that.attr('data-revert') !== 'undefined';
                    var ret;
                    if (that.prop('checked')) {
                        if (hasRevert) {
                            ret = 0;
                        } else {
                            ret = 1;
                        }
                    } else {
                        if (hasRevert) {
                            ret = 1;
                        } else {
                            ret = 0;
                        }
                    }
                    formData.info[name] = ret;
                } else if (type == 'radio') {
                    if (that.prop('checked')) {
                        formData.info[name] = that.val();
                    }
                } else {
                    formData.info[name] = that.val();
                }
            });

            $.ajax({
                url: submiturl,
                type: 'post',
                contentType: "application/json; charset=utf-8",
                dataType: 'json',
                data: JSON.stringify(formData),
                success: function (data) {
                    if (data.responseCode === '0000' && data.object) {
                        layer.open({
                            type: 1,
                            skin: 'com-popup',
                            area: '400px',
                            title:'提醒',
                            content: '<div class="compop-box">'+
                            '<h2>编辑商品信息成功</h2><p class="popup-btn"><a href="javascript:void(0)" ' +
                            'class="com-btn-03 color01 confirm-btn">确 认</a></p></div>',
                            success:function(){
                                $(".confirm-btn").click(function(){
                                    window.location.href = "/goods/usercenter/list";
                                });
                            },
                            cancel:function(){
                                window.location.href = "/goods/usercenter/list";
                            }
                        });
                        // Alert("提醒", "编辑商品信息成功", false, function () {
                        //
                        // });
                    } else {
                        Alert("错误", data.responseMsg);
                    }
                },
                error: function (data) {
                    Alert("错误", "网络错误或系统异常");
                },
                complete: function () {
                    resetBtn();
                }
            })
            return false;
        }
    });

})
`

**Comment by rbri** [comment] 2019-12-31 12:41
Sorry for bothering - but your post is more or less a collection of code fragments. What i need is a complete minimal sample working with real browsers and failing with HtmlUnit. Best will be to have a zip file with some files i can place on my local machine and i can open from the browser and from HtmlUnit to reproduce your problem.

Sorry, but my time is really limited and i have to focus on solving problems. Finding the problem within this large js code is already really time consuming.

**Comment by rbri** [comment] 2020-07-13 18:06
Sorry will close this for now. If you can provide a small sample i will try to help.

**Closed as completed by rbri** 2020-07-13 18:06 UTC
