### ISSUE TITLE
Freezing when opening website

### ISSUE THREAD

**Issue by insticore** [HtmlUnit/htmlunit#311] opened 2021-02-10 14:20 UTC
I'm trying to open this url [https://babibet.com/](https://babibet.com/), but JS executing just hangs

```
WebClient webClient = new WebClient();
webClient.getOptions().setJavaScriptEnabled(true);
webClient.getOptions().setCssEnabled(true);
webClient.getOptions().setDownloadImages(false);
webClient.getOptions().setRedirectEnabled(true);
            
webClient.getPage("https://babibet.com/sports")
```

HtmlUnit version is 2.47.1
```
        <dependency>
            <groupId>net.sourceforge.htmlunit</groupId>
            <artifactId>htmlunit</artifactId>
            <version>2.47.1</version>
        </dependency>
```

**Comment by rbri** [comment] 2021-02-10 19:06
Can you please check if this is a duplicate of #147

**Comment by insticore** [comment] 2021-02-11 06:19
@rbri yes this is similar problem, thanks, +1 for #147

**Comment by rbri** [comment] 2023-03-19 16:34
Looks like this page now also works with 3.0.0.

**Closed as completed by rbri** 2023-03-19 16:34 UTC
