### ISSUE TITLE
HtmlUnit is failing to load the full external JavaScript

### ISSUE THREAD

**Issue by JaviRpo** [HtmlUnit/htmlunit#93] opened 2019-10-23 06:05 UTC
The dependency version that I'm using is
```
<dependency>
	<groupId>org.junit.jupiter</groupId>
	<artifactId>junit-jupiter-api</artifactId>
	<version>5.5.2</version>
	<scope>test</scope>
</dependency>
```

The code that I have is:
```
try (WebClient webClient = new WebClient()) {
    webClient.getOptions().setThrowExceptionOnScriptError(false);
    HtmlPage htmlPage = webClient.getPage("https://www.exito.com/");

    DomNode domNode = htmlPage.querySelector(".menu-categoria");

    System.out.println(domNode); // domNode should not be null
}
```

After some tests, I realize that the problem is when the page is loading an external JavaScript in the URL https://cdn.polyfill.io/v3/polyfill.min.js?features=Object.keys&flags=gated,always
The problem is because of the JavaScript has in the first line a comment and space in the third character
![image](https://user-images.githubusercontent.com/8562436/67361745-22587000-f52f-11e9-94c2-8cffc3cdc840.png)

When I debug into the code the JavaScript `sourceCode` only has the first three characters
![image](https://user-images.githubusercontent.com/8562436/67361917-82e7ad00-f52f-11e9-9b94-9aa0bf0e8369.png)

And this is because the content is reading with `BOMInputStream`
![image](https://user-images.githubusercontent.com/8562436/67362402-8891c280-f530-11e9-8557-cbab0b446b0e.png)

**Comment by rbri** [comment] 2019-10-23 19:09
Many thanks for the detailed report.
Sorry but i can't reproduce your case. The final result (null) is the same here but the whole script is available.
Do you use the latest version?

**Comment by JaviRpo** [comment] 2019-10-23 19:24
@rbri I just realize that I posted my `junit` version 🤦‍♂ , not my `htmlunit` version
```
<dependency>
	<groupId>net.sourceforge.htmlunit</groupId>
	<artifactId>htmlunit</artifactId>
	<version>2.36.0</version>
</dependency>
```

Yes, I'm using the latest version.

How did you check to see the whole script is available?

**Comment by rbri** [comment] 2019-10-23 21:43
Strange i have no idea why you don't see the whole js  code

**Comment by JaviRpo** [comment] 2019-10-24 16:24
How did you check to see the whole script is available?

**Comment by rbri** [comment] 2019-10-24 20:29
Simply by placing a breakpoint and checking the sourceCode value

**Comment by JaviRpo** [comment] 2019-10-24 20:54
maybe a related Windows issue?

my windows version is
`Microsoft Windows [Version 10.0.17134.1069]`

and my java version is
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

What are yours?

**Comment by rbri** [comment] 2022-03-26 13:05
Sorry @JaviRpo to be that late on this. I fear the page has undergone some changes over the time. Did a quick test and it looks like major parts of the page are generated by javascript - and parts of the js code is failing because of the not perfect js support in HtmlUnit.
Will close this because it is too old.

Sorry

**Closed as completed by rbri** 2022-03-26 13:05 UTC
