### ISSUE TITLE
Don't process anymore when calling this javascript

### ISSUE THREAD

**Issue by j-shin** [HtmlUnit/htmlunit#489] opened 2022-07-11 12:08 UTC
The version is 2.50.0, but same issue on 2.62.0 also
This is test code
This `https://www.orami.co.id/` is using `https://cdn.seondf.com/js/v5/agent.js` javascript
When javascript engine execute `https://www.orami.co.id/` page and `https://cdn.seondf.com/js/v5/agent.js` script, the program stop
Don't occur any exception, Don't occur timeout, just stop the program then don't process next code.
In this code, it is not calling `System.out.println(htmlPage.getUrl());`
How can resolve this problem?

```
    public static void main(String[] args) {
        try (WebClient webClient = getWebClient()) {
            WebRequest request = new WebRequest(
                    new URL("https://www.orami.co.id/"));
            request.setTimeout(3000);
            webClient.setJavaScriptTimeout(3000);
            HtmlPage htmlPage = webClient.getPage(request);
            System.out.println(htmlPage.getUrl());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static WebClient getWebClient() {
        WebClient webClient = new WebClient(BrowserVersion.BEST_SUPPORTED);
        webClient.getOptions().setJavaScriptEnabled(true);
        webClient.getOptions().setRedirectEnabled(true);
        webClient.getOptions().setThrowExceptionOnScriptError(false);
        webClient.getOptions().setTimeout(1000);
        webClient.getOptions().setConnectionTimeToLive(1000);
        webClient.setJavaScriptTimeout(1000);
        return webClient;
    }
```

**Comment by black-snow** [comment] 2022-07-30 16:19
I can see it doing lots of things inside HtmlUnitRegExpProxy and I see some regex stuff happening in the JS. Could you provide an unminified, unuglyfied version of the JS?

**Comment by rbri** [comment] 2022-09-18 17:06
Have done a short test with the current snapshot and it looks like the problem is gone. Maybe the site has changed.

@j-shin please check if you see the same result

**Comment by rbri** [comment] 2024-03-27 11:33
no feedback will close this

**Closed as completed by rbri** 2024-03-27 11:33 UTC
