### ISSUE TITLE
Using WebClient Increases the Number of Active Threads

### ISSUE THREAD

**Issue by arashta** [HtmlUnit/htmlunit#95] opened 2019-11-03 12:10 UTC
I have implemented an automated HTML fetch unit that uses WebClient. 
`        Here is the latest format of my code:
        
        WebClient webClient = new WebClient(BrowserVersion.CHROME);
        try {
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            webClient.getOptions().setRedirectEnabled(true);
            webClient.getOptions().setThrowExceptionOnFailingStatusCode(true);
            webClient.getOptions().setUseInsecureSSL(true);
            webClient.getOptions().setTimeout(30000);
            webClient.setJavaScriptTimeout(30000);
            HtmlPage page = webClient.getPage(uri.toString());
            publishResource(articleTask, "OK", "text/html; charset=utf-8", page.asXml().getBytes("UTF-8"));
            page.cleanUp();
        } catch (Exception e) {
            log.warn("HTML UNIT processing failed : " + uri.toString());
        } finally {
           webClient.getJavaScriptEngine().shutdown();
            webClient.close();
            webClient.getCache().clear();
        }`

However, after a couple of hours, the number of active threads increases to 30K but there is no correlation with the accessed URIs, i.e., it is hard to reproduce the error if I rerun the module to fetch the exact same set of URIs.

The jstack output shows two groups of threads:
1) A group of threads that are RUNNABLE; an expmale stack trace:
"WebSocketClient@660754594-72059" #72059 daemon prio=5 os_prio=0 tid=0x00007ef4db91e000 nid=0x182a runnable [0x00007ef4f8c0c000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000134ad5aa8> (a sun.nio.ch.Util$3)
	- locked <0x0000000134ad5a98> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000134ad5970> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:464)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:401)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$1545/366265975.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
2) A group of threads that are waiting; an example stack trace:
"WebSocketClient@1373302039-72053" #72053 daemon prio=5 os_prio=0 tid=0x00007ef4db912800 nid=0x14a6 waiting on condition [0x00007ef4fa828000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000134bc1c08> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:392)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:858)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:783)
	at java.lang.Thread.run(Thread.java:748)

Also, after a couple of days, I get the following error message and all of the system resources are consumed:
**_Deadlocked thread: JS executor for com.gargoylesoftware.htmlunit.WebClient@6d1b0333_**

And this is the stack trace:
….javascript.JavaScriptEngine$HtmlUnitContextAction.run (JavaScriptEngine.java:866)

net.sourceforge.htmlunit.corejs.javascript.Context.call (Context.java:617)

…ceforge.htmlunit.corejs.javascript.ContextFactory.call (ContextFactory.java:534)

…htmlunit.javascript.HtmlUnitContextFactory.callSecured (HtmlUnitContextFactory.java:336)

…ware.htmlunit.javascript.JavaScriptEngine.callFunction (JavaScriptEngine.java:814)

…ware.htmlunit.javascript.JavaScriptEngine.callFunction (JavaScriptEngine.java:786)

…tware.htmlunit.html.HtmlPage.executeJavaScriptFunction (HtmlPage.java:2534)

…tware.htmlunit.html.HtmlPage.executeJavaScriptFunction (HtmlPage.java:2527)

…st.event.EventListenersContainer.executeEventListeners (EventListenersContainer.java:342)

…event.EventListenersContainer.executeAtTargetListeners (EventListenersContainer.java:379)

…e.htmlunit.javascript.host.event.EventTarget.fireEvent (EventTarget.java:171)

…software.htmlunit.javascript.host.Window.dispatchEvent (Window.java:2265)

…rgoylesoftware.htmlunit.javascript.host.Window$2$1.run (Window.java:2353)

net.sourceforge.htmlunit.corejs.javascript.Context.call (Context.java:617)

…ceforge.htmlunit.corejs.javascript.ContextFactory.call (ContextFactory.java:534)

…oylesoftware.htmlunit.javascript.host.Window$2.execute (Window.java:2358)

….javascript.JavaScriptEngine.doProcessPostponedActions (JavaScriptEngine.java:936)

…ftware.htmlunit.javascript.JavaScriptEngine.access$200 (JavaScriptEngine.java:104)

….javascript.JavaScriptEngine$HtmlUnitContextAction.run (JavaScriptEngine.java:880)

net.sourceforge.htmlunit.corejs.javascript.Context.call (Context.java:617)

…ceforge.htmlunit.corejs.javascript.ContextFactory.call (ContextFactory.java:534)

…htmlunit.javascript.HtmlUnitContextFactory.callSecured (HtmlUnitContextFactory.java:336)

…esoftware.htmlunit.javascript.JavaScriptEngine.execute (JavaScriptEngine.java:765)

…esoftware.htmlunit.javascript.JavaScriptEngine.execute (JavaScriptEngine.java:741)

…esoftware.htmlunit.javascript.JavaScriptEngine.execute (JavaScriptEngine.java:732)

…goylesoftware.htmlunit.html.HtmlPage.executeJavaScript (HtmlPage.java:922)

…e.htmlunit.html.HtmlScript.executeInlineScriptIfNeeded (HtmlScript.java:317)

…oftware.htmlunit.html.HtmlScript.executeScriptIfNeeded (HtmlScript.java:398)

com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute (HtmlScript.java:247)

…ware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage (HtmlScript.java:268)

…htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement (HTMLParser.java:798)

 org.apache.xerces.parsers.AbstractSAXParser.endElement (Unknown Source)

…htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement (HTMLParser.java:754)

…orge.htmlunit.cyberneko.HTMLTagBalancer.callEndElement (HTMLTagBalancer.java:1175)

…rceforge.htmlunit.cyberneko.HTMLTagBalancer.endElement (HTMLTagBalancer.java:1115)

…ge.htmlunit.cyberneko.filters.DefaultFilter.endElement (DefaultFilter.java:219)

….htmlunit.cyberneko.filters.NamespaceBinder.endElement (NamespaceBinder.java:303)

…it.cyberneko.HTMLScanner$ContentScanner.scanEndElement (HTMLScanner.java:3126)

…rge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan (HTMLScanner.java:2075)

…ourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument (HTMLScanner.java:922)

…sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse (HTMLConfiguration.java:438)

…sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse (HTMLConfiguration.java:389)

              org.apache.xerces.parsers.XMLParser.parse (Unknown Source)

…ware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse (HTMLParser.java:997)

    com.gargoylesoftware.htmlunit.html.HTMLParser.parse (HTMLParser.java:252)

com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml (HTMLParser.java:196)

…ylesoftware.htmlunit.DefaultPageCreator.createHtmlPage (DefaultPageCreator.java:268)

…argoylesoftware.htmlunit.DefaultPageCreator.createPage (DefaultPageCreator.java:159)

…argoylesoftware.htmlunit.WebClient.loadWebResponseInto (WebClient.java:531)

…tware.htmlunit.javascript.host.html.HTMLDocument.close (HTMLDocument.java:610)

          sun.reflect.GeneratedMethodAccessor389.invoke (Unknown Source)

        sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)

                        java.lang.reflect.Method.invoke (Method.java:498)

…ourceforge.htmlunit.corejs.javascript.MemberBox.invoke (MemberBox.java:174)

…ceforge.htmlunit.corejs.javascript.FunctionObject.call (FunctionObject.java:453)

…e.htmlunit.corejs.javascript.Interpreter.interpretLoop (Interpreter.java:1675)

…forge.htmlunit.corejs.javascript.Interpreter.interpret (Interpreter.java:1010)

…ge.htmlunit.corejs.javascript.InterpretedFunction.call (InterpretedFunction.java:111)

…ge.htmlunit.corejs.javascript.ContextFactory.doTopCall (ContextFactory.java:424)

…e.htmlunit.javascript.HtmlUnitContextFactory.doTopCall (HtmlUnitContextFactory.java:322)

…rge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall (ScriptRuntime.java:3628)

…esoftware.htmlunit.javascript.JavaScriptEngine$3.doRun (JavaScriptEngine.java:807)

….javascript.JavaScriptEngine$HtmlUnitContextAction.run (JavaScriptEngine.java:870)

net.sourceforge.htmlunit.corejs.javascript.Context.call (Context.java:617)

…ceforge.htmlunit.corejs.javascript.ContextFactory.call (ContextFactory.java:534)

…htmlunit.javascript.HtmlUnitContextFactory.callSecured (HtmlUnitContextFactory.java:336)

…ware.htmlunit.javascript.JavaScriptEngine.callFunction (JavaScriptEngine.java:814)

…e.htmlunit.javascript.host.xml.XMLHttpRequest.setState (XMLHttpRequest.java:213)

…are.htmlunit.javascript.host.xml.XMLHttpRequest.doSend (XMLHttpRequest.java:824)

…htmlunit.javascript.host.xml.XMLHttpRequest.access$000 (XMLHttpRequest.java:103)

…ware.htmlunit.javascript.host.xml.XMLHttpRequest$1.run (XMLHttpRequest.java:669)

net.sourceforge.htmlunit.corejs.javascript.Context.call (Context.java:617)

…ceforge.htmlunit.corejs.javascript.ContextFactory.call (ContextFactory.java:534)

….javascript.background.JavascriptXMLHttpRequestJob.run (JavascriptXMLHttpRequestJob.java:36)

…cript.background.JavaScriptJobManagerImpl.runSingleJob (JavaScriptJobManagerImpl.java:424)

…it.javascript.background.DefaultJavaScriptExecutor.run (DefaultJavaScriptExecutor.java:148)

                                   java.lang.Thread.run (Thread.java:748)

**Comment by rbri** [comment] 2019-12-21 09:52
Regarding the threads i fear this is a bug. What is missing so far is closing the WebSocket when the page goes away.
Will try to fix that.

**Comment by rbri** [comment] 2019-12-21 10:29
Have tried to make the code more robust.

Can you please check if you have some log output containing 'WS stop error'.

**Comment by rbri** [comment] 2019-12-21 12:59
Can you please try with the latest snapshot and report if the problem is still there. In general page.cleanUp() should close all associated web sockts

**Comment by rbri** [comment] 2020-04-26 11:38
No response from the reporter - will close this.

**Closed as completed** 2020-04-26 11:38 UTC
