### ISSUE TITLE
Location.getHref() throws MalformedURLException when location is "about:blank#foo"

### ISSUE THREAD

**Issue by atnak** [HtmlUnit/htmlunit#298] opened 2021-01-21 12:05 UTC
# Problem in brief

`java.net.MalformedURLException: unknown protocol: about` is thrown by [`Location.getHref()`](https://github.com/HtmlUnit/htmlunit/blob/026d0ebcfc6465b169d74f3676a6cb6de12b8fa5/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/Location.java#L182) when the location is `about:blank` and `location.hash` is also set.

# Reproducing

The code below:
* Prints `about:blank#foo` in Chrome / Firefox / Edge. 
* Prints `about:blank` in IE11.
* Throws the aforementioned `java.net.MalformedURLException: unknown protocol: about` exception in HtmlUnit 2.46.0.

```html
<html>
<head>
<script>
function test() {
    var iframe = document.getElementsByTagName('IFRAME')[0];

    iframe.contentWindow.location.hash = 'foo';
    console.log(iframe.contentWindow.location.href); // "about:blank#foo"
}
</script>
</head>
<body onload="test()">
<iframe src="about:blank"></iframe>
</body>
</html>
```

# Details

The exception is thrown by [this call to `UrlUtils.getUrlWithNewRef()`](
https://github.com/HtmlUnit/htmlunit/blob/026d0ebcfc6465b169d74f3676a6cb6de12b8fa5/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/Location.java#L196) because it is internally using a version of `new URL(...)` that does not support the `about` protocol.  Incidentally, the [variable `url` itself initially holds "about:blank"](https://github.com/HtmlUnit/htmlunit/blob/026d0ebcfc6465b169d74f3676a6cb6de12b8fa5/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/Location.java#L198) because unlike `getUrlWithNew*()`, `UrlUtils`'s other methods `toUrl*()` do support `about:blank`.

# Possible fixes

### Solution 1: Patch `Location.getHref()` with a hack for `about:blank`

```diff
     public String getHref() {
         final Page page = window_.getWebWindow().getEnclosedPage();
...
         try {
             URL url = page.getUrl();
             final boolean encodeHash = getBrowserVersion().hasFeature(JS_LOCATION_HREF_HASH_IS_ENCODED);
             final String hash = getHash(encodeHash);
             if (hash != null) {
+                if ("about:blank".equals(url.toExternalForm())) {
+                    return url.toExternalForm() + "#" + hash;
+                }
                 url = UrlUtils.getUrlWithNewRef(url, hash);
             }
             String s = url.toExternalForm();
```

### Solution 2: Change `UrlUtils` to better support `about:blank` across all its methods

```diff
 	private static URL createNewUrl(final String protocol, final String authority,
 			final String path, final String ref, final String query) throws MalformedURLException {
 
...
 		if (ref != null) {
 			if (ref.isEmpty() || ref.charAt(0) != '#') {
 				s.append('#');
 			}
 			s.append(ref);
 		}
 
-		return new URL(s.toString());
+		return toUrlUnsafe(s.toString());
 	}
```

**Comment by rbri** [comment] 2021-01-21 18:24
This seems to be a bit more difficult. Will have a look.

**Comment by rbri** [comment] 2021-01-24 08:55
> Prints about:blank#foo in Chrome / Firefox / Edge.

I can only reproduce this with chrome/edge, in FF i get a security error - do you agree?

The exception should be fixed - please have a look at the latest snapshot (will be available soon - see twitter).

**Comment by atnak** [comment] 2021-01-25 01:12
> in FF I get a security error - do you agree?

My bad, sorry, I oversimplified the test I gave you.  I've fixed by editing the original post with the following diff:

![image](https://user-images.githubusercontent.com/918211/105649968-8073c000-5ef5-11eb-8e8a-3e8c179ddf5b.png)

**Comment by rbri** [comment] 2021-01-25 07:05
I see, will check if this is still a issue

**Comment by rbri** [comment] 2021-01-25 16:31
i think this is fixed now; made a new Snapshot build available. Please reopen or open a new issue if you still have problems.

Many thanks for all the detailed reports and your support.

**Closed as completed by rbri** 2021-01-25 16:31 UTC
