### ISSUE TITLE
TypeError: Cannot modify readonly property: constructor

### ISSUE THREAD

**Issue by basimons** [HtmlUnit/htmlunit#537] opened 2022-12-22 08:56 UTC
I have been using htmlUnit on this specific website for a while to test our SAML login flow. A few days ago the test suddenly broke, without any changes from our end. Something probably changed on the website, but it is not working anymore. I was using 2.65.0 and updated to 2.67.0 to see if it fixed it, but unfortunately doesn't seem to do the trick.

A minimally reproducable example:
```
WebClient webClient = new WebClient(BrowserVersion.BEST_SUPPORTED);
webClient.getOptions().setThrowExceptionOnScriptError(false);
webClient.getOptions().setJavaScriptEnabled(true);

webClient.getPage("https://dev-43246762.okta.com/home/dev-43246762_blockbaxtest_1/0oa1a0d285rc8xFaS5d7/aln1a0gob9YTeiQMJ5d7");
webClient.waitForBackgroundJavaScript(10000);
HtmlPage okta = (HtmlPage) webClient.getCurrentWindow().getEnclosedPage();
webClient.waitForBackgroundJavaScript(10000);
```

Hope this is helpful, if not feel free to ask for more information.

**Comment by rbri** [comment] 2022-12-22 11:17
Looks like an duplicate of #238.
@basimons  can you please try with the latest snapshot and report your observations here

**Comment by basimons** [comment] 2022-12-22 12:05
That indeed fixes it! Thanks a lot for your quick feedback.

Do you have any idea when 2.68.0 will be released? 
If its soon I'll just wait with adding the snapshot to production and update it once released.

**Comment by rbri** [comment] 2022-12-22 12:11
the plan is to do it this year :-)
maybe after xmas.

**Closed as completed** 2022-12-22 12:11 UTC
