### ISSUE TITLE
Selenium 4.3.0: cannot access HasInputDevice

### ISSUE THREAD

**Issue by snicoll** [HtmlUnit/htmlunit#490] opened 2022-07-15 10:06 UTC
An upgrade to the latest Selenium release leads to the following:

```
> Task :spring-boot-project:spring-boot-test:compileJava
/Users/snicoll/workspace/work/spring-boot/main/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/web/htmlunit/webdriver/LocalHostWebConnectionHtmlUnitDriver.java:33: error: cannot access HasInputDevices
public class LocalHostWebConnectionHtmlUnitDriver extends WebConnectionHtmlUnitDriver {
       ^
  class file for org.openqa.selenium.interactions.HasInputDevices not found
1 error
```

**Comment by rbri** [comment] 2022-07-16 10:59
Sorry, this is a duplicate of https://github.com/SeleniumHQ/htmlunit-driver/issues/119.
Work on this has started, hopefully a beta will be available soon.

**Closed as completed by rbri** 2022-07-16 10:59 UTC
