### ISSUE TITLE
StackOverflowError on WebClient.getPage

### ISSUE THREAD

**Issue by smatei** [HtmlUnit/htmlunit#156] opened 2020-04-16 11:52 UTC
URL: https://sustainability.asu.edu/person/angela-gonzales
version: 2.39.1
VM arguments: -Xmx4096m

The following code throws java.lang.StackOverflowError after more than 10 minutes . 

`

    WebClient client = null;
    try
    {
      client = new WebClient();
      client.getOptions().setCssEnabled(false);
      client.getOptions().setJavaScriptEnabled(false);
      client.getOptions().setTimeout(20000);

      Page page = client.getPage("https://sustainability.asu.edu/person/angela-gonzales");
      if (page != null && page.isHtmlPage())
      {
        HtmlPage htmlPage = (HtmlPage) page;
        System.out.println("html page downloaded");
        System.out.println(htmlPage.asText());
      }
    }
    catch (Throwable e)
    {
      e.printStackTrace();
    }
    finally
    {
      if (client != null)
      {
        client.close();
      }
    }
`

![image](https://user-images.githubusercontent.com/17740806/79452487-e63f2d00-7ff0-11ea-9879-c44ff8e1d4d9.png)

`

java.lang.StackOverflowError
	at com.gargoylesoftware.htmlunit.html.FrameWindow.getTopWindow(FrameWindow.java:77)
	at com.gargoylesoftware.htmlunit.html.FrameWindow.getTopWindow(FrameWindow.java:77)
	at com.gargoylesoftware.htmlunit.html.FrameWindow.getTopWindow(FrameWindow.java:77)
	at com.gargoylesoftware.htmlunit.html.FrameWindow.getTopWindow(FrameWindow.java:77)
	at com.gargoylesoftware.htmlunit.html.FrameWindow.getTopWindow(FrameWindow.java:77)
	...........
	at com.gargoylesoftware.htmlunit.html.FrameWindow.getTopWindow(FrameWindow.java:77)
	at com.gargoylesoftware.htmlunit.html.FrameWindow.getTopWindow(FrameWindow.java:77)
	at com.gargoylesoftware.htmlunit.html.FrameWindow.getTopWindow(FrameWindow.java:77)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.getBaseURL(HtmlPage.java:2316)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.getFullyQualifiedUrl(HtmlPage.java:699)
	at com.gargoylesoftware.htmlunit.html.BaseFrameElement.loadInnerPageIfPossible(BaseFrameElement.java:182)
	at com.gargoylesoftware.htmlunit.html.BaseFrameElement.loadInnerPage(BaseFrameElement.java:124)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadFrames(HtmlPage.java:1919)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:251)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:561)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:420)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:337)
	at com.gargoylesoftware.htmlunit.html.BaseFrameElement.loadInnerPageIfPossible(BaseFrameElement.java:198)
	at com.gargoylesoftware.htmlunit.html.BaseFrameElement.loadInnerPage(BaseFrameElement.java:124)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadFrames(HtmlPage.java:1919)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:251)
	.........
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:561)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:420)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:337)
	at com.gargoylesoftware.htmlunit.html.BaseFrameElement.loadInnerPageIfPossible(BaseFrameElement.java:198)
	at com.gargoylesoftware.htmlunit.html.BaseFrameElement.loadInnerPage(BaseFrameElement.java:124)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadFrames(HtmlPage.java:1919)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:251)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:561)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:420)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:337)
	at com.gargoylesoftware.htmlunit.html.BaseFrameElement.loadInnerPageIfPossible(BaseFrameElement.java:198)
	at com.gargoylesoftware.htmlunit.html.BaseFrameElement.loadInnerPage(BaseFrameElement.java:124)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadFrames(HtmlPage.java:1919)
`

**Comment by rbri** [comment] 2020-04-16 18:39
I think i found the reason for this and was also able to create a test case.
Will work on the fix during the next days.

Thanks for the report.

**Comment by rbri** [comment] 2020-04-17 18:49
Ok, regarding the reason - you  have disabled js and the page contains a noscript tag that contains a iframe like this

    <noscript>
        <iframe src=" ?    cn=ot&amp;...."style="display:none;width:0px;height:0px"></iframe>
    </noscript>

In fact this results in a call to the same url as the page itself but with a different query string. And this returns the page including a noscript tag.... and so on.

BTW this looks like one of the spy snippets like to be informed about the peoples not having js enabled also.

The trick in this case is the response for the iframe includes an X-Frame-Options: DENY header and this was ignored by HtmlUnit so far.

Have done some implementation and test for this. At the moment the ci build is running and if there are ne new errors i will make a new snapshot available soon (check twitter).

**Comment by rbri** [comment] 2020-04-17 18:49
Outside of the fix itself i have to do some more work here to include more security check.

**Comment by smatei** [comment] 2020-04-17 19:11
We are using this in our test environment for analysing the content of some SERP result urls for advancedwebranking.com. The error triggered a massive memory spike. In order to avoid it we enabled JavaScript. It will take more cpu, but we are still testing. We will decide later how we run it in live environment. Cpu cost on Amazon AWS will decide it. But with JavaScript it would be more accurate. I will be watching for the new snapshot.

**Comment by rbri** [comment] 2020-04-19 08:27
Fixed with the latest snapshot build. Please try and inform me about your results.

**Comment by smatei** [comment] 2020-04-21 07:43
It works now, both javascript enabled and disabled for https://sustainability.asu.edu/person/angela-gonzales

But I found another url, https://www.bizjournals.com/phoenix/bio/2711/Angela+Gonzales that messes up the memory when javascript is enabled

![javascript-enabled-memory](https://user-images.githubusercontent.com/17740806/79839168-cdea5c00-83bc-11ea-8087-178417760439.png)

Please check this case too. Until then I will disable javascript.

**Comment by rbri** [comment] 2020-04-21 10:38
Can you please open another issue - the root cause seems to be totally different.

**Comment by smatei** [comment] 2020-04-23 07:51
I have found another url, http://israelmatzav.blogspot.com/ that triggers stackoverflow when javascript is disabled. It has some iframes in it. 

![image](https://user-images.githubusercontent.com/17740806/80072219-9dd2c280-854e-11ea-87f1-c4b2af6aa4f5.png)

and the iframe source http://www.jpost.com/JPTools/NewsTicker.aspx redirects to https://www.jpost.com//LandedPages/NewsTicker.aspx that has another iframe with http://www.jpost.com/JPTools/NewsTicker.aspx and so on. It might be helpful to have only some limited levels of iframes or keep a set of visited iframes so that we avoid an iframe visited twice.

![image](https://user-images.githubusercontent.com/17740806/80072656-38330600-854f-11ea-8d66-82ab04f0b780.png)

![image](https://user-images.githubusercontent.com/17740806/80071772-de7e0c00-854d-11ea-8ac1-834c5df83013.png)

**Comment by rbri** [comment] 2020-04-23 18:16
Yes another funny case. Have written some test and will try to fix it.

**Closed as completed** 2020-04-24 09:35 UTC
