### ISSUE TITLE
Cannot call method "getElementsByClassName" of undefined 

### ISSUE THREAD

**Issue by sowjanyaboddeti** [HtmlUnit/htmlunit#199] opened 2020-07-27 09:29 UTC
`EcmaError: lineNumber=[5] column=[0] lineSource=[          const prevButton = carousel.parentElement.getElementsByClassName("carousel-previous-button")[0];] name=[TypeError] sourceName=[https://www.fdic.gov/assets/javascript/carousels.js] message=[TypeError: Cannot call method "getElementsByClassName" of undefined (https://www.fdic.gov/assets/javascript/carousels.js#5)]
com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot call method "getElementsByClassName" of undefined (https://www.fdic.gov/assets/javascript/carousels.js#5)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:891)
        at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:619)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
        at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354)`

Getting the above JavaScript exception when trying to scrape https://www.fdic.gov/news/press-releases/2020/

**Comment by rbri** [comment] 2020-07-28 06:25
Will have a look / do you use the latest version of HtmlUnit?

**Comment by sowjanyaboddeti** [comment] 2020-07-28 06:26
Yes, I have used 2.42.0 version.

**Comment by rbri** [comment] 2020-07-28 08:28
Which browser do you simulate?

**Comment by sowjanyaboddeti** [comment] 2020-07-28 08:52
I tried Chrome & Firefox.

**Comment by rbri** [comment] 2020-07-28 19:15
Ok, can reproduce your problem and was able to build a simple sample.
Have an idea what goes wrong here - looks like a major problem with HtmlUnits Rhino usage/customization.
Will require some time to write more test and fix this.

Thanks for the report, nice catch....

**Comment by sowjanyaboddeti** [comment] 2020-07-29 08:39
Hey, Thanks for looking into this. 
If it is not too much to ask do you any estimation of how bigger this fix could be and how long it could take to fix it.?
Or is there any alternate browser version I can use to temporarily avoid this issue?

Thanks again :)

**Comment by rbri** [comment] 2020-07-29 09:15
Will try to get this done during this week.

**Comment by rbri** [comment] 2020-08-02 12:14
Just made a new snapshot build available. Your problem should be fixed with this version - please try and update this. There is at least one problem left but i have opened another issue for this.

**Comment by sowjanyaboddeti** [comment] 2020-08-03 07:42
Though I am not seeing the JS exception with latest snapshot build (2.43.0-SNAPSHOT), the webpage doesn't load completely. Does your change just ignores the exception? Why am I not able to render the Javascript for this particular URL?

**Comment by rbri** [comment] 2020-08-03 17:28
> Does your change just ignores the exception?

You think i need a whole week only to suppress the exception?

The page includes several js parts - usually huge js scripts. It will not be that easy to figure out why some js parts are working different from real browsers. If you like to get this fixed you can help to nail down the problem to the problematic function. You can have a look at https://htmlunit.sourceforge.io/submittingJSBugs.html for some hints how to do it.

**Comment by sowjanyaboddeti** [comment] 2020-08-04 04:30
Thanks for your help! I had that doubt because the javascript exception seemed like an issue with server-side code. I am not sure how feasible it would be to fix it at the client-side. Though I am not getting any JS exceptions now,  I will try to nail-down the problematic function if it would help in fixing the issue.

Also, Should I use AJAX Controller? Would that be of any help?

I am a beginner in using HTMLUnit, I really appreciate your help so far, Thank you.

**Comment by rbri** [comment] 2021-11-12 11:32
sorry looks like i missed your last question. Hope you have solved the problem and still use HtmlUnit.

Will close this - please open a new issue if you still have problem.

**Closed as completed by rbri** 2021-11-12 11:32 UTC
