### ISSUE TITLE
HtmlUnit with report generator: get Report body after generation

### ISSUE THREAD

**Issue by felixh85** [HtmlUnit/htmlunit#374] opened 2021-08-20 14:43 UTC
I want to use the Java HtmlUnit library to generate a BIRT report in HTML. However, BIRT shows a process bar while the data is loaded from the database and assembled on the page. When I am opening the BIRT report with HtmlUnit, only the page with the process bar is returned but the report content information remains empty.
The returned HTML page contains a div `<DIV` ID="Document" `CLASS="birtviewer_document_fragment"></DIV>` which is empty but should be getting filled by the report generator. However, whatever I do, I don't get this "Document" Div filled with data.
I am using the following code:

    WebClient webClient = new WebClient(BrowserVersion.CHROME);
    HtmlPage page=null;
    try {
        page = webClient.getPage("https://....");
        webClient.waitForBackgroundJavaScript(60000);
        System.out.println("Waiting 5 secs.....");
        synchronized (page) {
            page.wait(5000);
        }
    } catch (FailingHttpStatusCodeException | IOException | InterruptedException e) {
        e.printStackTrace();
    }
    DomElement oe = page.getElementById("Document");
    System.out.println(oe.getChildElementCount());
    webClient.close();

As output I am always getting 0 for the number of children of the Document div. When I print the HTML source code of the page, I always get the empty Document div.
I tried using window.animateAnimationsFrames() after webClient.waitForBackgroundJavaScript(60000) but the pending frames are 0 and the final result is the same as before.
What am I doing wrong? Could someone please put me in the right direction. Thank you.

**Comment by rbri** [comment] 2021-08-21 12:41
Without a test page is will be hard to do anything here. Maybe you can create a simple war file with a simple report that reproduces the problem?

**Comment by felixh85** [comment] 2021-08-24 06:33
I have contacted you via your webmaster email. Please reply and I send you a link for testing.

**Comment by rbri** [comment] 2021-09-15 17:56
Ok, no i have some hints what might going wrong here. The Library send a SOAP request for getting the data and the request fail with a server error 500. The problem seems to be the sent request body - looks like HtmlUnit does something wrong during construction of this.
Will analyze .... please be patient.

**Comment by rbri** [comment] 2021-09-15 18:30
Looks like sending an XMLDocument via XMLHttpRequest differs in HtmlUnit from real browsers.
Will write some unit test and then try to fix it.

**Comment by felixh85** [comment] 2021-09-16 13:44
Thanks a lot for your effort.

**Comment by rbri** [comment] 2021-09-17 07:55
You're welcome.
Was able to get the result page yesterday  based on some quick hacks.
So there is hope to get this solved soon.

**Comment by rbri** [comment] 2021-09-17 14:37
From the spec:

From the spec: If body is a Document, then set this’s request body to body, serialized, converted, and UTF-8 encoded. 

Have done a first impl of this and i'm now able to open the report.

Many, many thanks for this isssue - i guess this was a problem for many applications.

**Comment by rbri** [comment] 2021-09-17 15:07
Fixed in git - will make a new snapshot build available soon (check https://twitter.com/htmlunit).

Enjoy HtmlUnit and feel free to report more interesting bugs.

**Closed as completed by rbri** 2021-09-17 15:07 UTC
