### ISSUE TITLE
IllegalStateException: No script object associated with the Page

### ISSUE THREAD

**Issue by asolntsev** [HtmlUnit/htmlunit#68] opened 2019-08-12 21:37 UTC
I guess it happens when
1. A page with frames is being parsed, and
2. One of frames changes URL 
3. Then HtmlUnit tries to generate an "unload" event for the page which is not fully parsed yet (and therefore has `getScriptableObject() == null`).

I have a reproducible case in Selenide framework: https://github.com/selenide/selenide/blob/master/src/test/java/integration/FrameWaitTest.java

Try to run it several times: it fails time-to-time with the following error:

```java
org.openqa.selenium.WebDriverException: java.lang.IllegalStateException: No script object associated with the Page. class: 'com.gargoylesoftware.htmlunit.html.HtmlPage' url: 'http://127.0.0.1:14702/page_with_frames.html' content: <!DOCTYPE html>
<html lang="en">
<head>
  <title>Test::frames</title>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<frameset rows="80,*" cols="*">
  <frame src="hello_world.txt" name="topFrame" id="top-frame" scrolling="no" noresize>
  <frameset cols="300,*">
    <frame src="page_with_dynamic_select.html" name="leftFrame" scrolling="no" noresize>
    <frame src="page_with_jquery.html" name="mainFrame">
    <frame src="page_with_parent_frame.html" name="parentFrame">
  </frameset>
</frameset>
</html>

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Andreis-MacBook-Pro.local', ip: 'fe80:0:0:0:4a3:96eb:183c:fbf%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_144'
Driver info: driver.version: HtmlUnitDriver
selenide.url: http://127.0.0.1:14702/page_with_frames_with_delays.html?browser=htmlunit&timeout=4000
selenide.baseUrl: http://127.0.0.1:14702

	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:722)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$get$8(HtmlUnitDriver.java:687)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$runAsync$0(HtmlUnitDriver.java:429)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No script object associated with the Page. class: 'com.gargoylesoftware.htmlunit.html.HtmlPage' url: 'http://127.0.0.1:14702/page_with_frames.html' content: <!DOCTYPE html>
<html lang="en">
<head>
  <title>Test::frames</title>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<frameset rows="80,*" cols="*">
  <frame src="hello_world.txt" name="topFrame" id="top-frame" scrolling="no" noresize>
  <frameset cols="300,*">
    <frame src="page_with_dynamic_select.html" name="leftFrame" scrolling="no" noresize>
    <frame src="page_with_jquery.html" name="mainFrame">
    <frame src="page_with_parent_frame.html" name="parentFrame">
  </frameset>
</frameset>
</html>

	at com.gargoylesoftware.htmlunit.html.DomNode.getScriptableObject(DomNode.java:922)
	at com.gargoylesoftware.htmlunit.javascript.host.event.Event.<init>(Event.java:215)
	at com.gargoylesoftware.htmlunit.javascript.host.event.BeforeUnloadEvent.<init>(BeforeUnloadEvent.java:69)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeEventHandlersIfNeeded(HtmlPage.java:1217)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.isOnbeforeunloadAccepted(HtmlPage.java:1291)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:371)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:315)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:704)
	... 5 more
```

**Comment by Mahagoon** [comment] 2020-03-06 09:54
Hello

Did you solved the problem in any way. We have a similar problem in our selenium tests and don’t know how to fix it so far.

**Comment by asolntsev** [comment] 2020-03-06 11:43
@Mahagoon no, we still haven't solved it. :(

**Comment by rbri** [comment] 2020-09-18 07:04
Can you please provide the content of all the involveld artifacts (e.g. page_with_dynamic_select.html). I think i  found at least one place that might be the reason for that.
But i need to write a unit test to fix this finally.

**Comment by asolntsev** [comment] 2020-09-21 20:47
@rbri Sorry, it was a flaky test, quite hard to reproduce.

**Comment by rbri** [comment] 2020-09-22 18:52
Can i close this?

**Comment by BASSEMALMAHW** [comment] 2020-10-14 14:21
I need  an answer to this problem. this issue very important for me

**Comment by rbri** [comment] 2020-10-14 16:30
Sorry but i need a case to reproduce this. Do you use the latest version of HtmlUnit?

**Comment by asolntsev** [comment] 2020-10-14 17:45
@rbri hi. Sorry for the long delay. I will soon send you my code for reproducing the issue

**Comment by rbri** [comment] 2020-10-14 18:29
great, thanks

**Comment by BASSEMALMAHW** [comment] 2020-10-15 06:53
I'm using the 2.33 version of HtmlUnit....

**Comment by asolntsev** [comment] 2020-10-15 15:25
@rbri @BASSEMALMAHW Hi. I found a way to stably reproduce the problem:
1. `git clone --branch reproduce-htmlunit-issue-68 https://github.com/selenide/selenide.git`
2. `cd selenide`
3. `./gradlew test`

Expected output:
> Task :test FAILED
> 200 tests completed, 12 failed

In the failed tests, you will see the error: 
> org.openqa.selenium.WebDriverException: java.lang.IllegalStateException: No script object associated with the Page. class: 'com.gargoylesoftware.htmlunit.html.HtmlPage' url: 'http://127.0.0.1:3834/hello_world.txt' content: Hello, WinRar!

**Comment by rbri** [comment] 2020-10-15 17:49
Thanks for the test case, i can reproduce your results. Will try to make a plain HtmlUnit testcase out of this and hopefully this will still show the error.

**Comment by rbri** [comment] 2020-10-16 12:04
@asolntsev @BASSEMALMAHW have published a new snapshot build - can you please test if your problem is gone with this snapshot

**Comment by rbri** [comment] 2020-10-16 12:33
And for documentation - this was a race condition; the page was available via window.getEnclosedPage before the page initialization was complete.

**Comment by asolntsev** [comment] 2020-10-16 13:40
@rbri What version have you released? 

1. I have tried `net.sourceforge.htmlunit:htmlunit:2.45.0-SNAPSHOT`, and got the same error:
> java.lang.IllegalStateException: No script object associated with the Page. class: 'com.gargoylesoftware.htmlunit.html.HtmlPage' url: 'http://127.0.0.1:48612/page_with_jquery.html' content: <!DOCTYPE html>

2. When I also added `org.seleniumhq.selenium:htmlunit-driver:2.45.0-SNAPSHOT`, all errors got fixed. 

Yihhaaa!

P.S. I also committed dependency update to my branch `reproduce-htmlunit-issue-68` in https://github.com/selenide/selenide.git

**Comment by rbri** [comment] 2020-10-16 13:51
Sounds strange - the fix is in HtmlUnit and not in the driver.

**Comment by asolntsev** [comment] 2020-10-16 13:57
@rbri Well, it's probably because of transitive dependencies. `htmlunit-driver:2.44.0` transitively fetches some older versions of `htmlunit-2.40.0.jar`, `neko-htmlunit-2.40.0.jar` and `htmlunit-cssparser-1.5.0.jar`.

**Comment by rbri** [comment] 2020-10-16 15:15
sounds reasonable - thanks

**Closed as completed** 2020-10-16 17:11 UTC
