### ISSUE TITLE
javascript don't work

### ISSUE THREAD

**Issue by hunannan** [HtmlUnit/htmlunit#11] opened 2019-01-09 09:52 UTC
Hi, I have a html,the url is http://www.suxf.cn/test/index1.html 。this is blank html,but there three javascript files inside, I use htmlunit 2.33 of version to execute 。there is a request  "http://smt.admaster.com.cn/p.gif?........." when use chrome browser open the url。there isn't the request,when use htmlunit 2.33 。please help me ，tks。

**Comment by hunannan** [comment] 2019-01-09 09:54
![1](https://user-images.githubusercontent.com/14331360/50891597-978f0480-1437-11e9-8e4e-e45024b3f763.jpg)
the chrome request Image。

**Comment by hunannan** [comment] 2019-01-09 09:55
BrowserVersion.BrowserVersionBuilder browserVersionBuilder = new BrowserVersion.BrowserVersionBuilder(BrowserVersion.FIREFOX_60);
             browserVersionBuilder.setBrowserLanguage("zh-cn");
             browserVersionBuilder.setSystemLanguage("zh-cn");
             browserVersionBuilder.setUserLanguage("zh-cn");


            WebClient webClient = new WebClient(browserVersionBuilder.build());
            webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            webClient.getOptions().setCssEnabled(false);
            webClient.getOptions().setActiveXNative(false);
              webClient.getOptions().setDownloadImages(true);
             webClient.addRequestHeader("Accept-Language", "zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3");


            webClient.setJavaScriptTimeout(1000 * 60);
            webClient.getOptions().setJavaScriptEnabled(true);
            webClient.getOptions().setUseInsecureSSL(true);
            webClient.getOptions().setCssEnabled(false);
            webClient.getOptions().setRedirectEnabled(true);
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            webClient.setAjaxController(new NicelyResynchronizingAjaxController());
            webClient.getOptions().setTimeout(1000 * 60);
            webClient.waitForBackgroundJavaScript(60 * 1000);
            webClient.getOptions().setDoNotTrackEnabled(true);


            try {
                String url = "http://www.suxf.cn/test/index1.html";
                final HtmlPage htmlPage = webClient.getPage(url);
                System.out.println(htmlPage.asXml());

                webClient.waitForBackgroundJavaScript(15000);

**Comment by rbri** [comment] 2019-01-09 18:23
This looks really strange/interesting to me.
I can reproduce your finding but i have no idea why the real browser load this image.
Can you simplify your test page a bit more to find out which part of the page triggers the image request.

**Comment by hunannan** [comment] 2019-01-10 01:12
> This looks really strange/interesting to me.
> I can reproduce your finding but i have no idea why the real browser load this image.
> Can you simplify your test page a bit more to find out which part of the page triggers the image request.

Hi ，Thank you for your prompt reply。
    the page triggers the image request  on the attachment。
By the way，How to set the browser resolution and  If the browser resolution is set, the JavaScript on the page can be read to。
Here's my code，But it doesn't seem to work。

 webClient.getOptions().setScreenWidth(800);
 webClient.getOptions().setScreenHeight(600);
webClient.getCurrentWindow().setInnerWidth(800);
 webClient.getCurrentWindow().setInnerHeight(600);
webClient.getCurrentWindow().setOuterHeight(800);
webClient.getCurrentWindow().setOuterHeight(600);


 


![1](https://user-images.githubusercontent.com/14331360/50939225-ef208500-14b6-11e9-8473-27323fb825f3.jpg)
![2](https://user-images.githubusercontent.com/14331360/50939227-f182df00-14b6-11e9-9df7-f80feafb45bc.jpg)
![3](https://user-images.githubusercontent.com/14331360/50939511-2479a280-14b8-11e9-9c30-c1c1ba0f13ee.jpg)

**Comment by xiangfengsu** [comment] 2019-01-10 10:12
@rbri @hunannan 
Hello, I have encountered the same problem, I may have found the problem, because the new Image() object does not write the onload method. I write 2 test pages.


[Write the img.onload method page](http://www.suxf.cn/test/a/test_img_onload.html)

![image](https://user-images.githubusercontent.com/9291534/50961363-83fca000-1502-11e9-8f70-299ac97ccfdc.png)
Log output
![image](https://user-images.githubusercontent.com/9291534/50961410-a55d8c00-1502-11e9-9a77-221e4ca093b9.png)

[Did not write the img.onload method page](http://www.suxf.cn/test/a/test_no_img_onload.html)
![image](https://user-images.githubusercontent.com/9291534/50961443-b9a18900-1502-11e9-8081-653eb247021b.png)
No log output


Is I need to set a method or a bug in htmlunit?  
Thank you~ ~

**Comment by rbri** [comment] 2019-01-10 16:59
@xiangfengsu: regarding image loading: this works as designed. HtmlUnit is a headless browsers, and there is no reason the load the image if it is not used anywhere. But because some dirty tricks are based on the processing of the onload handler, HtmlUnit loads the image if an onload handler is available.

See HTMLImageElement2Test for some test cases.

Do you can think of a case where this is not correct?

**Comment by rbri** [comment] 2019-01-10 17:01
@hunannan will have a look at this during the next days. Maybe the script tag does not load the script automatically. From a quick look i guess at least some test cases are missing.

**Comment by rbri** [comment] 2019-01-10 17:02
@hunannan regarding setting the screen resolution. Please open a new issue and add some sample js code to make your expectations clear.

**Comment by rbri** [comment] 2019-01-10 17:36
@hunannan: have added a test for the way the script is loaded in your case. Works with HtmlUnit.

Do you know if 'c' is an script or an image tag in step 3?

**Comment by xiangfengsu** [comment] 2019-01-11 02:01
@rbri I see, thank you~ ~

**Comment by rbri** [comment] 2019-03-29 18:28
Have done some more work on image resolving if handlers are defined.
You can also force htmlunit to resolve all images by using

`com.gargoylesoftware.htmlunit.WebClientOptions.setDownloadImages(boolean)`

Will close this issue, please inform if you still have problem.

**Closed as completed by rbri** 2019-03-29 18:28 UTC
